language: node_js
cache: bundler
sudo: false
branches:
  only:
    - gh-pages # test gh-pages
    - /(.*)/   # test all branches
before_script:
  - npm install -g jsonlint
  - bundle install
script: jsonlint -q iiif-universe.json && bundle exec ./validate.rb
